SELECT DISTINCT EMAIL
FROM EMAIL_TABLE, DATA_TABLE
WHERE EMAIL_TABLE.JOIN_ID = DATA_TABLE.JOIN_ID 
AND DATA_TABLE.COLUMN_1%2 = 0
AND DATA_TABLE.COLUMN_2 < DATA_TABLE.COLUMN_1
AND DATA_TABLE.COLUMN_3 LIKE '%1'

-- RESULT: 1867945546@theinformationlab.nl